sonar.language=java
sonar.coverage.jacoco.xmlReportPaths=source/target/site/jacoco/jacoco.xml
sonar.host.url=${env.SONARQUBE_HOST_URL}
sonar.login=${env.SONARQUBE_TOKEN}
sonar.projectKey=${env.CI_PROJECT_NAME}
sonar.qualitygate.wait=true
sonar.java.binaries=source/target/classes
sonar.java.test.binaries=source/target/test-classes
sonar.sources=source/src/main/java
sonar.tests=source/src/test/java
