server:
  port: 8042

management:
  server:
    port: 9040

spring:
  application:
    name: "@project.artifactId@"
    environment: dev
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      properties:
        "schema.registry.url": "http://localhost:8081"

component-config:
  participant:
    accountId: 'eudb%'
    reportType: PARTICIPANT
    reports:
      - name: TAR030
        reportName: TAR030
      - name: TAR108
        reportName: TAR108
      - name: TSR107
        reportName: TSR107
      - name: TSR109
        reportName: TSR109
      - name: RJ092
        reportName: RJ092
      - name: RJCT000
        reportName: RJC092
      - name: WARN000
        reportName: WRN106
      - name: RECS
        reportName: RECS
    reports_custom:
      - name: RECS
        reportName: RECS
  regulator:
    accountId: 'eudr%'
    reportTypeEsma: ESMA
    reportTypeFca: FCA
    reports:
      - name: TAR030
        reportName: TAR030
        report_query_eod: TRAR000
      - name: TAR108
        reportName: TAR108
        report_query_eod: MRAR000
      - name: TSR107
        reportName: TSR107
        report_query_eod: TRTS000
      - name: TSR109
        reportName: TSR109
        report_query_eod: MRTS000
      - name: RJ092
        reportName: RJ092
        report_query_eod: RJ092
      - name: RJCT000
        reportName: RJC092
        report_query_eod: RJCT000
      - name: WARN000
        reportName: WRN106
        report_query_eod: WARN000
      - name: RECS
        reportName: RECS
        report_query_eod: RECO000
      - name: RECI
        reportName: RECI
        report_query_eod: RECO000
      - name: TPST000
        report-name: TPST000
        report-query-eod: POSC
  tr:
    accountId: 'tr%'
    reportType: TR
    reportTypeQuery:
      - RL078
      - TD107
    reports:
      - name: RL078
        reportName: RL078
      - name: TD107
        reportName: TD107
  sla:
    validator:
      enabled: true
    entity:
      customer:
        - name: TAR030
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: TAR108
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: TSR107
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: TSR109
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: RJ092
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: RJCT000
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: WARN000
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
        - name: RECS
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT06:00:00Z
      authority:
        - name: TAR030
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: TAR108
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: TSR107
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: TSR109
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: RJ092
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: RJCT000
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: WARN000
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: RECS
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: RECI
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
      tr:
        - name: RL078
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z
        - name: TD107
          sla-init: yyyy-MM-ddT00:00:00Z
          sla-end: yyyy-MM-ddT12:00:00Z

  csv:
    output_path: "work-repository-observability/upload/item35/"
  topics:
    observability-item-topic: rft.dev.observability.item.private.v1
    observability-item-consumer-group-id: rft.dev.rft-observability-item35-creator
  kududb-control:
    schema: EMIR_REFIT_DEV_CONTROL_REFIT
  kududb-account:
    schema: EMIR_REFIT_DEV_ACCOUNT_MNG
    blockSize: 50
  cloudera:
    knox-auth: true
    cpu:
      enabled: false
      selectCpu: select cpu_percent_across_hosts where category=CLUSTER
      desiredRollup: DAILY
    ram:
      enabled: false
      selectRam: select physical_memory_used
      selectTotalRam: select physical_memory_total
      desiredRollup: DAILY
    storage:
      enabled: false
      selectTotalApi: select total_capacity_across_filesystems
      selectFreeApi: select total_capacity_free_across_filesystems
      desiredRollup: DAILY
      entityName: dm-rftemir-light-qa

logging:
  level:
    root: INFO
    "org.apache.kafka": INFO
    "com.sixgroup.refit": INFO

rft:
  kafka:
    tracing:
      consumer:
        enabled: true
      producer:
        enabled: true
