server:
  port: 8040

management:
  server:
    port: 9040

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    properties:
      "schema.registry.url": "http://localhost:8081"
  datasource:
    kududb:
      driver-class-name: ""
      jdbc-url: ""
      username: ""
      password: ""
    sqlserverdb:
      driver-class-name: ""
      jdbc-url: ""
      username: ""
      password: ""
    jpa:
      hibernate:
        ddl-auto: validate
component-config:
  csv:
    output_path: "work-repository/write/"

logging:
  level:
    root: INFO
    "org.apache.kafka": INFO
    "com.sixgroup.refit": DEBUG
