apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rft-observability-item35

resources:
  - namespace.yaml
  - reports-pvc.yaml
  - kafka-alias-service.yaml
  - deployment.yaml
  - service.yaml
