apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rft-observability-item35-reports
  namespace: rft-observability-item35
  labels:
    app.kubernetes.io/name: rft-observability-item35-creator
    app.kubernetes.io/managed-by: argocd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
