apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rft-observability-item35-creator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.six-group.net/six/rftemir/rft/components/backend/rft-observability/rft-observability-item35-creator.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: rft-observability-item35
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
